# Generated by Django 6.0.5 on 2026-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
